modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "ingotcraft"
version = "1.19.2-2.3.1-forge"
displayName = "IngotCraft"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ingotcraft"
logoFile = "logo.png"
authors = "jahirtrap"
description = "Easy crafting for base metals"
itemIcon = "ingotcraft:steel_ingot"

[[dependencies.ingotcraft]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.ingotcraft]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,1.20)"
    ordering = "NONE"
    side = "BOTH"
