modLoader = "javafml"
loaderVersion = "[45,)"
license = "All Rights Reserved"

[[mods]]
modId = "ingotcraft"
version = "${file.jarVersion}"
displayName = "IngotCraft"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ingotcraft"
logoFile = "logo.png"
authors = "jahirtrap"
description = "Easy crafting for base metals"
itemIcon = "ingotcraft:steel_ingot"

[[dependencies.ingotcraft]]
    modId = "forge"
    mandatory = true
    versionRange = "[45,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.ingotcraft]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.4,1.20)"
    ordering = "NONE"
    side = "BOTH"
