modLoader = "javafml"
loaderVersion = "[37,)"
license = "All Rights Reserved"

[[mods]]
modId = "ingotcraft"
version = "1.17.1-2.3.1-forge"
displayName = "IngotCraft"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ingotcraft"
logoFile = "logo.png"
authors = "jahirtrap"
description = "Easy crafting for base metals"
itemIcon = "ingotcraft:steel_ingot"

[[dependencies.ingotcraft]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.ingotcraft]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17.1,1.18)"
    ordering = "NONE"
    side = "BOTH"
